global using FluentAssertions;
global using Heroes.LocaleText;
global using Heroes.XmlData.Source;
global using Heroes.XmlData.StormData;
global using Heroes.XmlData.StormDepotCache;
global using Heroes.XmlData.StormMods;
global using NSubstitute;
global using System.IO.Abstractions.TestingHelpers;
global using System.Xml.Linq;
